# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default
variables:
  - name: COVERITY_TOOL_HOME
    value: C:\Test\cov-analysis-win64-2024.9.1

jobs:
- job: SAST
  displayName: 'SAST Analysis'
  steps:
  - script: cov-capture --dir idir --source-dir .
  - script: cov-analyze --dir idir --all --all-security
  - script: cov-commit-defects --dir idir --url https://coverity.field-test.blackduck.com --auth-key-file C:/Test/auth-key.txt --stream java-pipe-ryan
#- job: SARIF
#  dependsOn: BAC
#  steps:
  - script: cov-format-errors --dir idir --json-output-v10 issues.json
  - script: C:\Test\cov-analysis-win64-2024.9.1\node\node.exe C:\Test\cov-analysis-win64-2024.9.1\SARIF\cov-format-sarif-for-github.js --inputFile issues.json --outputFile issue-report.sarif --githubUrl https://github.com --repoName autumn0914/java-sec-code-demo --checkoutPath autumn0914/java-sec-code-demo . 033dbbad71a9d2923ac6cca7b3c62e8d4aa1e5ef
  - script: tar -a -c -f  CodeAnalysisLogs.zip issue-report.sarif
  - task: PublishBuildArtifacts@1
    displayName: 'Publish SARIF Report'
    inputs:
      PathtoPublish: 'issue-report.sarif'
      ArtifactName: CodeAnalysisLogs

- job: SCA
  dependsOn: SAST
  displayName: 'SCA Analysis'
  steps:
    - script: java -jar C:\Test\BDDetect\detect-10.3.0.jar --blackduck.url=https://sca.demo.blackduck.com --blackduck.trust.cert=true --blackduck.api.token=NmUyNjJlOTgtZWIyYi00YWY3LTg1YTYtMWQ0NDQzODNkNTk2Ojc2ZTdiYjE5LWRmZDYtNDQ2Ny05YmFlLTgwY2RjMGUwZWM4Zg==  --detect.source.path=$(System.DefaultWorkingDirectory) --detect.project.name=InsecBank --detect.project.version.name=2.0